<a href="https://colab.research.google.com/github/Muqtarali/AUTO_COLD-MAIL-GEN-/blob/upload-sanitized/Encoding%20Categorical%20Data/Encoding_Categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/customer.csv')

In [ ]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df = df.iloc[:,2:]
df.head()

  purchased
0        No
1        No
2        No
3        No
4        No

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['purchased']),df['purchased'],test_size=0.2)

In [ ]:
x_train.head()

     review education
9      Good        UG
16     Poor        UG
0   Average    School
25     Good    School
34  Average    School

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

# Re-initialize x_train and x_test to their original string-based DataFrame format
# to ensure OrdinalEncoder receives the correct input type.
# Using a random_state for reproducibility.
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['purchased']),
    df['purchased'],
    test_size=0.2,
    random_state=0
)

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

# Fit and transform the data
oe.fit(x_train)
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [ ]:
x_train_df=pd.DataFrame(x_train,columns=df.drop(columns=['purchased']).columns)
x_train_df.head()

   review  education
0     2.0        2.0
1     0.0        0.0
2     0.0        2.0
3     1.0        0.0
4     2.0        0.0

# Lable encoding

```

```

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)

y_train=le.fit_transform(y_train)
y_test=le.fit_transform(y_test)

In [ ]:
le.classes_

array([0, 1])

In [ ]:
y_train_df=pd.DataFrame(y_train,columns=['purchased'])
y_train_df.head()

   purchased
0          1
1          1
2          0
3          0
4          0

# One hot Encoding

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# Using Pandas

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-1

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# Using Sklearn

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(drop='first')

In [ ]:
x_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
x_train_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
x_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()

In [ ]:
np.hstack((X_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 35000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 1.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 1.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
data=pd.DataFrame(np.hstack((X_train[['brand','km_driven']].values,x_train_new)))
data.head()

          0       1    2    3    4    5    6    7    8
0   Hyundai   35000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1      Jeep   60000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
2   Hyundai   25000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3  Mahindra  130000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
4   Hyundai  155000  1.0  0.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
counts = df['brand'].value_counts()

In [ ]:
df['brand'].nunique()
threshold = 100
repl = counts[counts <= threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7816,False,False,False,False,False,False,False,True,False,False,False,False,False
5433,False,False,False,False,False,False,False,False,False,True,False,False,False
3024,False,False,False,False,False,True,False,False,False,False,False,False,False
2098,False,False,False,False,False,False,False,False,False,False,False,False,True
771,False,False,False,True,False,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# 1. Initialize OneHotEncoder with infrequent category handling
ohe = OneHotEncoder(
     min_frequency=101,           # Threshold is 100, so < 101 flags infrequent items
    handle_unknown='uncommon', # Safely manages new unseen brands
    sparse_output=False         # Returns a dense array (like get_dummies) instead of sparse matrix
)

# 2. Assign OHE to your specific column(s)
transformer = ColumnTransformer(
    transformers=[
        ('brand_ohe', ohe, ['brand'])
    ],
    remainder='passthrough'     # Keeps all other columns in your dataframe intact
)

# 3. Fit and transform the data
# Returns a clean DataFrame with your OHE columns
encoded_array = transformer.fit_transform(df)
encoded_cols = transformer.get_feature_names_out()
df_encoded = pd.DataFrame(encoded_array, columns=encoded_cols)

# 4. View a random sample of 5 rows
df_encoded.sample(5)


# Column Transformer

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# Corrected ColumnTransformer setup
ct = ColumnTransformer(
    transformers=[  # <--- Fixed the typo here
        ('tnf1', SimpleImputer(), ['fever']),
        ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city']),
    ],
    remainder='passthrough'
)

In [ ]:
X_train_new=ct.fit_transform(X_train)
X_test_new=ct.transform(X_test)